### ISSUE TITLE
Document core concepts

### ISSUE THREAD

**Issue by JosephSalisbury** [giantswarm/inago#10]
We have a few core concepts (groups, group instances, group slices, directory structure), that I'd like to get some solid documentation on.

**Comment by JosephSalisbury** [comment]
ping @xh3b4sd @zeisss

**Comment by xh3b4sd** [comment]
Please link what we have so far.

**Comment by JosephSalisbury** [comment]
As a dump from our discussion:

```
- group - many unit files
  - a group is named after the directory its unit files live in
  - should be able to treat a group as a unit - abstract away unit
- group slice - a scalable group instance
- group instance - a group in a fleet cluster
```

```
- Can submit groups as slices or just as plain units (group “instance”)
- Groups are represented as folders containing the unitfiles
  - Groups must not have the same prefix as other groups
- Unitfiles must start with the group name
- Use spf13/cobra + Pflag
- Use https://github.com/giantswarm/formica
```

**Comment by xh3b4sd** [comment]
A group is a collection of unit files that are scheduled on the same host.

**Comment by JosephSalisbury** [comment]
I'd argue this is already satisfied by what we have in `docs/`. @giantswarm/cena thoughts?

**Comment by zeisss** [comment]
We maybe want to add a page about the idea of update and what that means e.g. for sliceable groups vs instance groups.

**Comment by Nesurion** [comment]
done with #173
