### ISSUE TITLE
Add to homebrew repository

### ISSUE THREAD

**Issue by zeisss** [giantswarm/inago#100]
Our users just want to do `brew install inago`.

**Comment by JosephSalisbury** [comment]
We'll need to wait till _after_ we release to do this, as we'll need to upload a binary to S3.
Then, it's just a case of adding a formula to https://github.com/giantswarm/homebrew-swarm

**Comment by JosephSalisbury** [comment]
Actually, it would be better to use the release tarball, if we can.

**Comment by JosephSalisbury** [comment]
Also, let's update the release notes after we have this all set up

**Comment by JosephSalisbury** [comment]
And the readme!
