### ISSUE TITLE
Do some test deployments on Leaseweb

### ISSUE THREAD

**Issue by zeisss** [giantswarm/inago#101]
To see if we actually need caching and/or retries already, lets do some deployments against slow/full systems, like our leaseweb deployment.
- [x] Validate we need caching or retries
- [ ] Create issues and/or PRs

**Comment by zeisss** [comment]
First check on Testcluster, maybe then live

Do ghostbuster, appd

**Comment by zeisss** [comment]
Blocked by #174 if you are lazy

**Comment by JosephSalisbury** [comment]
@xh3b4sd I'm going to close this, after the testing we did on Wednesday.

**Comment by zeisss** [comment]
@JosephSalisbury Whats the result? what did you deploy? did it work?

**Comment by xh3b4sd** [comment]
We deployed the elastic search example back and forth. Even you did @zeisss

**Comment by JosephSalisbury** [comment]
Sorry, I'm being lazy.

We deployed the elasticsearch example (using our private elasticsearch image, mind) onto leaseweb, and performed a rolling update (without data loss). And it worked! :tada: 

In terms of additional work, we did note https://github.com/giantswarm/inago/issues/213, which we decided was not a blocker.
