### ISSUE TITLE
Ensure we can manage instance groups

### ISSUE THREAD

**Issue by zeisss** [giantswarm/inago#104]
Instance as in groups with unslicable, maybe global units.
- [x] Ensure code works (submit, start, stop, destroy)
- [ ] Updates work with max-growth=0 min-alive=0
- [ ] Updates throw a nice error with max-growth > 0
- [ ] Updates throw a nice error with min-alive > 0
- [ ] UnitTests
- [x] Integration Tests
- [x] Add examples (k8)

**Comment by zeisss** [comment]
:white_check_mark:  Just doing `inagoctl update` returns an error

```
Kallisto:example zeisss$ ../inagoctl --fleet-endpoint=http://172.17.8.101:49153 update simple
2016-03-22 16:20:33.229 | ERROR    | context.Background: Failed to update group 'simple'. (update not allowed: cannot update unsliceable group)
```

This error currently comes for every combination of arguments for `inagoctl update`.

**Comment by JosephSalisbury** [comment]
with

```
core@core-01 ~ $ ls -R .
.:
inagoctl  simple

./simple:
simple-unit.service
core@core-01 ~ $ cat ./simple/simple-unit.service
[Unit]
Description=Inago Demo Unit

[Service]
ExecStart=/bin/bash -c "while true; do echo Hi; sleep 10; done"
```
- :white_check_mark: submit, start, stop and destroy all work
- :x: update with max-growth=0 and min-alive=0, gives:

```
core@core-01 ~ $ ./inagoctl update simple --max-growth=0 --min-alive=0
2016-03-29 10:28:42.154 | ERROR    | context.Background.WithValue("task-id", "4b1254ea-69fc-4ceb-9a9f-efeac70b54a3"): controller: error encountered updating: update not allowed: cannot update unsliceable group
2016-03-29 10:28:44.155 | ERROR    | context.Background: Failed to update group 'simple'. (update not allowed: cannot update unsliceable group)
```
- :x: updates don't throw a nice error with max-growth > 0, because the "cannot update unsliceable group" error fires

```
core@core-01 ~ $ ./inagoctl update simple --max-growth=100
2016-03-29 10:33:29.460 | ERROR    | context.Background.WithValue("task-id", "28b30138-6ede-4155-896b-14ff68bfab2b"): controller: error encountered updating: update not allowed: cannot update unsliceable group
2016-03-29 10:33:31.461 | ERROR    | context.Background: Failed to update group 'simple'. (update not allowed: cannot update unsliceable group)
```
- :x: updates don't throw a nice error with min-alive > 0 - it would be better if it was more explicit

```
core@core-01 ~ $ ./inagoctl update simple --min-alive=100
[{/usr/code/.gobuild/src/github.com/giantswarm/inago/cli/update.go:87: } {/usr/code/.gobuild/src/github.com/giantswarm/inago/controller/controller.go:398: update not allowed: cannot have minimum alive units greater than current number of units}]
```

@zeisss I'm going to make some explicit issues for the three problems we have here, and then close this, yeah?
I don't know what you want with the "UnitTests" checkbox, fyi.

**Comment by JosephSalisbury** [comment]
- generally updating instance groups: https://github.com/giantswarm/inago/issues/186
- error message on updating instance groups with max-growth > 0: https://github.com/giantswarm/inago/issues/187
- error message on updating instance groups with min-alive > 0: https://github.com/giantswarm/inago/issues/188

**Comment by zeisss** [comment]
I guess having any errors at all is the goal here. 

UnitTests) Just add a test to check that update throws an error, so we don' t accidentally add code in the future that makes it work.

**Comment by JosephSalisbury** [comment]
okay cool, that should be folded in as part of the more explicit tickets
