### ISSUE TITLE
Log Level Definition / Meaning

### ISSUE THREAD

**Issue by Nesurion** [giantswarm/inago#130]
I'd like to clarify in which cases we use which log level.
Our logger implementation provides the following log level:

```
        Debug(ctx context.Context, f string, v ...interface{})
    Info(ctx context.Context, f string, v ...interface{})
    Notice(ctx context.Context, f string, v ...interface{})
    Warning(ctx context.Context, f string, v ...interface{})
    Error(ctx context.Context, f string, v ...interface{})
    Critical(ctx context.Context, f string, v ...interface{})
```

ping @giantswarm/cena

**Comment by JosephSalisbury** [comment]
this is what i've been (mentally) working with:
- `Critical`: cases where human intervention is required to stop catastrophic failure (think: losing all units in a cluster) - i haven't seen a good reason to use this yet
- `Error`: an error has occurred (i've been sticking this in `err != nil` blocks)
- `Warning`: something potentially bad has happened (not an error, but you should look into it)
- `Notice`: i haven't used this
- `Info`: general information that is useful to a user (this is the default level)
- `Debug`: anything we need to debug stuff, but wouldn't be useful to a day-to-day user

**Comment by Nesurion** [comment]
sounds good to me. should we put a short definition in a comment above the functions in the interface?
https://github.com/giantswarm/inago/blob/master/logging/logging.go#L12

**Comment by JosephSalisbury** [comment]
Yeah, that sounds good.

**Comment by Nesurion** [comment]
closing in favor of issue https://github.com/giantswarm/inago/issues/132
