### ISSUE TITLE
destroy should support slices

### ISSUE THREAD

**Issue by zeisss** [giantswarm/inago#149]
`update` just threw an error and I ended up with a third stopped slice I didn't want to have. `inagoctl destroy mygroup@a8a` didn't work, it reported unit not found. I suspect destroying slices is not supported.

**Comment by Nesurion** [comment]
It seems that the problem is caused by not detecting the `@a8a` part as the slice ID. The request against is the controller looks like this:

```
controller.RequestConfig{Group:"mygroup@c77", SliceIDs:[]string{}}
```

I'd say we need to fix that in the cli, since the request is just doesn't make sense like this.

**Comment by Nesurion** [comment]
I guess we could either:
:a: parse the `mygroup@3e3` to `controller.RequestConfig{Group:"mygroup", SliceIDs:3e3}`
:b: provide the group and the slice as separate command line arguments:
`$ inagoctl destroy mygroup 3e3`

**Comment by zeisss** [comment]
+1 for :a:

**Comment by JosephSalisbury** [comment]
+1 for :a: , we should be able to split on "@"

**Comment by Nesurion** [comment]
I'd argue that going with :a: also means that there will be no way to provide more than one slice ID when running the command. (we could introduce a separator like `,`. But that feels ugly)
Option :b: would allow that in a clean way:
`inagoctl destroy <group> [sliceID...]`
`inagoctl destroy mygroup 3e3 abc`

**Comment by JosephSalisbury** [comment]
i think `inagoctl destroy mgroup@3e3 mygroup@abc` isn't a bad solution - if anything, you're probably going to be copying these out of a status output anyway.

I think this would be more consistent with the other commands, too

**Comment by Nesurion** [comment]
agreed on the copy-paste from status argument.
But in terms of other commands, I'd argue that the submit command defaults to number of slices to 1, but you are able to overwrite that by providing the desired number.

**Comment by JosephSalisbury** [comment]
I meant more with regards to start/stop, you can provide multiple group slices there

**Comment by Nesurion** [comment]
Going with option :a: : 
By using fleetctl one gets used to addressing the things managed by fleet (so units) with the name and the ID separated by the @ sign.
Since inago abstracts units into groups, it is more consistent to use the same naming pattern for the smallest thing managed by the tool (in this case groups).

**Comment by Nesurion** [comment]
destroy support sliceIDs done with #180 
start/stop support sliceIDs done with #182
