### ISSUE TITLE
Fix failing integration tests

### ISSUE THREAD

**Issue by JosephSalisbury** [giantswarm/inago#154]
See: https://travis-ci.org/giantswarm/inago/jobs/117454270

`002-update.t` and `004-update.t` are both failing.

**Comment by JosephSalisbury** [comment]
ping @zeisss

**Comment by zeisss** [comment]
Might be #153

**Comment by zeisss** [comment]
Although https://travis-ci.org/giantswarm/inago/jobs/117454270#L290-L312 is a different thing.

**Comment by zeisss** [comment]
#156 helped a lot.
