### ISSUE TITLE
ReadySec is just a sleep, afterwards is no status check

### ISSUE THREAD

**Issue by zeisss** [giantswarm/inago#155]
The idea behind `readySecs` is, that this must be the minimum number of seconds the slice must be alive. If the slice dies in that time, the update should fail.

**Comment by zeisss** [comment]
We actually need to test this, since the status is read somewhere afterwards, but it is not explicit.

**Comment by xh3b4sd** [comment]
Do we have evidence that this is actually broken? There is a check. See https://github.com/giantswarm/inago/blob/master/controller/update.go#L111

**Comment by zeisss** [comment]
@xh3b4sd no, no evidence. I just looked at the code and was very confused. I had the feeling that this somehow worked because it just blocked longer.

Still, the discussion: There is an explicit feature connected to `readySec`. Should we make it explicit in the code?

**Comment by xh3b4sd** [comment]
Please elaborate. 

How to make this more explicit?

**Comment by zeisss** [comment]
Adding a status check, which throws an error after the `Sleep` would be an option

**Comment by xh3b4sd** [comment]
IMO we already do this.

**Comment by zeisss** [comment]
ping @giantswarm/cena opinions please

**Comment by JosephSalisbury** [comment]
yeah, we check that the units are running after we update them, so i think this is fine

**Comment by JosephSalisbury** [comment]
@giantswarm/cena - Is there any action required on this?

**Comment by zeisss** [comment]
seems not so. Lets close this.
