### ISSUE TITLE
Verify no-need-for-update check works if units are not scheduled onto machine

### ISSUE THREAD

**Issue by zeisss** [giantswarm/inago#158]
https://travis-ci.org/giantswarm/inago/jobs/117487767 fails and reports an "units already up to date", although the test clearly modifies the local file. Maybe our check here is broken when the units are not scheduled correctly onto machines?

**Comment by xh3b4sd** [comment]
This issue is quite old and AFAIK our integration test suite is doing well. Is this still valid? If so, can you elaborate a little bit more on the actual problem?

**Comment by zeisss** [comment]
I can't even see the error in that job anymore. Hard to investigate. Lets close this.
