### ISSUE TITLE
=== RC1 ===

### ISSUE THREAD

**Issue by zeisss** [giantswarm/inago#165]
Lets make RC1, so we can get feedback.
- [x] Merge https://github.com/giantswarm/inago/pull/162
- [x] Merge https://github.com/giantswarm/inago/pull/163
- [x] Merge https://github.com/giantswarm/inago/pull/173
- [x] Merge https://github.com/giantswarm/inago/issues/114
- [x] Search and replace for `formica`
- [x] Write, get a thumbs up on release notes
- [x] Create GitHub release, title as `RC1` (make a minor release)
- [x] Add to Homebrew tap (https://github.com/giantswarm/inago/issues/100)
- [x] Internal Giant Swarm announcement
- [x] Coreos-Users Mailinglist Email (Ask for Feedback) (https://github.com/giantswarm/inago/pull/179)

**Comment by JosephSalisbury** [comment]
@puja108 is handling the coreos users mailing list, so i'm gonna close this.

Hurrah for releasing things! :tada:
