### ISSUE TITLE
Expand update unit testing coverage

### ISSUE THREAD

**Issue by JosephSalisbury** [giantswarm/inago#171]
https://github.com/giantswarm/inago/pull/162 introduced a fair amount of testing, but we can do better.

**Comment by xh3b4sd** [comment]
Looking at the coverage it currently looks not that bad. Anything left we want to do here?

**Comment by JosephSalisbury** [comment]
If you're happy with it, I'm happy with it. The new update integration test stuff helps.

**Comment by xh3b4sd** [comment]
Lets close this then.
