### ISSUE TITLE
Support more than http api or local domain socket

### ISSUE THREAD

**Issue by zeisss** [giantswarm/inago#174]
For our production servers, we are not exposing fleet over http, not even within the VPN. So to use inago there, we would need to copy it over along with the unit files to one of the servers and execute it remotely. 

These are unnecessary steps. OpenSSH ships domain socket proxying with [6.7](https://lwn.net/Articles/609321/), but thats not in the standard version of OS X. Any other hints how to use this more easily?

**Comment by JosephSalisbury** [comment]
@zeisss I wouldn't mind a more descriptive title

**Comment by zeisss** [comment]
e.g. Fleetctl supports doing domain sockets over ssh IIRC

**Comment by xh3b4sd** [comment]
I would simply go the fleetctl way. It works. It is there. Having a look should ease the implementation here.

**Comment by zeisss** [comment]
please merge #200 and make a n pr for the integration tests.

**Comment by zeisss** [comment]
Lets close this when the integration tests are there.

**Comment by JosephSalisbury** [comment]
Closing via https://github.com/giantswarm/inago/issues/204
