### ISSUE TITLE
Updating an instance group with max-growth > 0 should show a nice error message

### ISSUE THREAD

**Issue by JosephSalisbury** [giantswarm/inago#187]
When updating an instance group, max-growth > 0 is nonsensical, as the group cannot scale, by definition. If the user attempts to update an instance group with max-growth > 0, a nice error message should be printed.

**Comment by xh3b4sd** [comment]
Again the term instance group is confusing to me. What is this issue about? Is this already covered in https://github.com/giantswarm/inago/blob/474a3d620556e6d6ecb4b5a351cc6e7dc21d5559/controller/controller.go#L358 ?

**Comment by JosephSalisbury** [comment]
Instance group == an unsliced group. E.g: test-unit.service. I'm not certain what our update support is like for this right now, though.

**Comment by xh3b4sd** [comment]
Is the condition then simply "if numRunning is 1and maxGrowth is 0, throw an error"?

**Comment by JosephSalisbury** [comment]
Not exactly. With group slices (sliceable groups), we _can_ grow them. With group instances (unsliceable groups), we can't grow them. In that latter case, specifying a max-growth is incorrect.

**Comment by JosephSalisbury** [comment]
So, more "if group is not sliceable, and maxgrowth > 0"

**Comment by xh3b4sd** [comment]
For me the result would be the same. Why would we want to prevent killing all instances for a "none-sliced" group but not for a "sliced" group? Why making a difference between slicable or not?

**Comment by JosephSalisbury** [comment]
The update strategy is different between sliceable and unsliceable groups.

With sliceable groups, we can grow as much as we want, as long as we respect min-alive.
With unsliceable groups (although, updating these isn't supported yet https://github.com/giantswarm/inago/issues/186), we can't grow - we need to remove and add. so, in this case, max-growth doesn't make sense.

**Comment by xh3b4sd** [comment]
> With sliceable groups, we can grow as much as we want, as long as we respect min-alive.

This is not true when `maxGrowth` is set to `0`, and this issue is about exactly that setting. So again, where is the difference?

**Comment by JosephSalisbury** [comment]
```
17:19] 
Joe Salisbury so
[17:20] 
with sliceable groups, max growth can be greater than zero. with unsliceable groups, it cannot be more than zero
[17:20] 
Tim Schindler Why?
[17:21] 
Joe Salisbury well, sliceable groups is obvious
[17:21] 
with unsliceable groups, the reason they’re unsliceable is because you can’t run multiple instances
[17:21] 
so, we can’t grow
[17:22] 
Tim Schindler We could, but the user probably don't want to because it is about a service that cannot be or must not be scaled.
[17:22] 
That makes sense.
[17:22] 
Joe Salisbury well yes, we ​_could_​
[17:22] 
but we shouldn't
```
