### ISSUE TITLE
Example: Elasticsearch

### ISSUE THREAD

**Issue by zeisss** [giantswarm/inago#192]
We want to determine whether the current inago feature set is sufficient for setting up a production-ish ELK logging set up. If it is, we should work on the example; if it isn't, we need to determine what features are missing. This issue tracks the work of determining that.
- Elasticsearch
- Kibana
- Logstash-Forwarder (global)

**Comment by zeisss** [comment]
Look at what releaseit does here.

**Comment by xh3b4sd** [comment]
I looked at the unit files created by releaseit. My main concern was that we do only support `.service` unit types. 

This is my releaseit command to check the unit files.

```
releaseit create monitoring --group=xxx --dry-run --dry-run-path=tmp --env=stage/prod --stack=foo --provider aws
```

My thoughts.
- Depending on the used storage we are fine. AFAIK when using local storage we need `.mount` unit files. 
- Releaseit also creates the `elasticsearch-curator`, which uses a `.timer` unit to continuously cleanup old data. 
- We may could ignore that particular fact for a minimal example. AFAIK it is possible to handle global units with Inago. 

Anyway, I don't think the fix to support all kinds of unit types would be that expensive. Overall I think it should be possible to provide an ES example with little improvements in Inago.

**Comment by zeisss** [comment]
@xh3b4sd FYI: Releaseit now has an `export-inago-path` flag in the `./releaseit create` command.

**Comment by zeisss** [comment]
ping @giantswarm/cena

**Comment by JosephSalisbury** [comment]
current todo:
- [ ] Sort out the elasticsearch group
- [ ] Write an example for it

**Comment by JosephSalisbury** [comment]
@xh3b4sd i've stolen assignment :D
