### ISSUE TITLE
Make builder minor release

### ISSUE THREAD

**Issue by zeisss** [giantswarm/inago#202]
Since we changed the var in #91 we should do a release of builder. Please also provide a nicer response in #87 to teemow after this was published.

**Comment by JosephSalisbury** [comment]
We might as well wait till https://github.com/giantswarm/builder/issues/88 is fixed

**Comment by JosephSalisbury** [comment]
er @zeisss - why's this in the `inago` repository? :D

**Comment by zeisss** [comment]
yeah, to check you are awake. Closing for builder#93

**Comment by JosephSalisbury** [comment]
<3
