### ISSUE TITLE
Add back max attempts failed check

### ISSUE THREAD

**Issue by JosephSalisbury** [giantswarm/inago#209]
If an update command locks up - i.e: it keeps trying to add / remove slices, we should abort the update.

**Comment by zeisss** [comment]
Example:
Having a unit that conflicts with itself. If you try to create more slices than there are available machines, it blocks forever, as the unit never gets loaded.

**Comment by JosephSalisbury** [comment]
Slight clarification - the max attempts failed check was specifically on the update command - in this failure mode where we can neither add nor remove slices.

Submitting conflicting units is slightly seperate, in that that's more to do with us waiting on units to enter a state that they never can.

**Comment by JosephSalisbury** [comment]
This case only happens when both `isGroupRemovalAllowed` and `isGroupAdditionAllowed` return (false, nil), and no other work can occur. 
In this case, slices can neither be added nor removed, and the update loops _eternally_.

The max attempts failed check would (eventually) cause this to halt. Saying that, if this case occurs, we should fix the issue with `isGroupRemovalAllowed` and `isGroupAdditionAllowed`, not have some extra machinery that gets in the way.

So, closing - we don't need it, and if we did need it, it's because another thing is broken.
