### ISSUE TITLE
Improve locations of unit files for walkthroughs

### ISSUE THREAD

**Issue by JosephSalisbury** [giantswarm/inago#219]
The kubernetes walkthrough is in `docs`, and the unit files are in `example`. We need to decide if we want to keep them in seperate locations, or unify them.

**Comment by zeisss** [comment]
ping @puja108 opinion?

**Comment by puja108** [comment]
yeah, it seems kinda strange keeping them apart, don't have a very strong opinion on this, maybe @marians has as he has put some thoughts into how to show `docs` directly on the the website. I'd kinda like to have them together, but I don't know how that works together with the `docs` on website implementation.

**Comment by marians** [comment]
IMHO `/docs` should only contain markdown content and images to be shown inside these markdown pages.

**Comment by puja108** [comment]
Then maybe we should link over somehow? For example:
- Links from the .mds to the example direcotries
- A README in the `examples` directory that links out to the howto .mds
  Thoughts?

**Comment by marians** [comment]
Linking is fine, ideally only from `docs` to `examples`, not vice versa. And please use absolute URLs (`http://github.com/...`).

**Comment by puja108** [comment]
@marians what would be a reason for not (also) linking from `examples` to `docs`? When I browse the git and see there's examples I'll be in that folder and if there's nothing in there telling me there's docs for some of these examples, I might never for look for them.

**Comment by marians** [comment]
The only reason I can think of is that the canonical location for the docs should be at giantswarm.io/products/inago/... at some point. Not really a good reason to prevent links to the docs subfolder, I admit.

**Comment by puja108** [comment]
Addressing this for the k8s example in https://github.com/giantswarm/inago/pull/239

**Comment by puja108** [comment]
adressed completely in #239
