### ISSUE TITLE
k8s example should use containers

### ISSUE THREAD

**Issue by puja108** [giantswarm/inago#226]
currently it's running binaries directly

**Comment by zeisss** [comment]
why?

**Comment by puja108** [comment]
Because we (try to) deploy all our infrastructure modules in containers and their easier to maintain and update compared to binary based unit files?

**Comment by hectorj2f** [comment]
"Everybody" uses systemd units on which the k8s binaries are launched

**Comment by hectorj2f** [comment]
Well, you can sometimes find some examples with docker containers.... poor people https://github.com/coreos/etcd/pull/4106/files

**Comment by puja108** [comment]
I'm not on any side of this argument, I was just of the impression that it would be nicer style to use containers, but I'm ok if there's good arguments for binaries and this is closed.

**Comment by puja108** [comment]
In https://github.com/giantswarm/inago/pull/239 I moved to @hectorj2f's containers, which I also updated to include the latest full release (all images contain following tags: 1.0.1, 1.0.2, 1.2.0, 1.2.2)

**Comment by puja108** [comment]
done
