### ISSUE TITLE
get k8s example to be able to be updated

### ISSUE THREAD

**Issue by puja108** [giantswarm/inago#227]
For a first release this does not need to be fully HA (or rather zero downtime), yet. However, @JosephSalisbury mentioned that we could use the "conflicts + n group slices trick" to get updates working.

**Comment by zeisss** [comment]
This is a workaround. I would vote against this. 

It doesn't work when adding more machines. We could instead use the unit-replicator or just wait until we have implemented that logic into the inago itself.

**Comment by puja108** [comment]
I thought the result of the product planning was that we do the workaround now and the right implementation in a following step/version. Or did I understand @teemow wrong?

**Comment by zeisss** [comment]
IIRC we just go with the global agents we already have, mention that this is not good, that we internally use fleet-unit-replicator (which is now open-source) and will extend Inago in the future to handle this in one tool.

**Comment by puja108** [comment]
Ok, just so I understand that correctly, if we do a `inagoctl update` on a global unit it goes through but it implies some downtime (takes down all units and replaces them with new ones), right?

**Comment by puja108** [comment]
https://github.com/giantswarm/inago/pull/239 fixes this at least for the nodes. The api server still is not HA and has downtimes while updating, which is less severe as k8s does not rely on the api server to stay up.

**Comment by puja108** [comment]
fixed
