### ISSUE TITLE
Golint Stutter Warnings

### ISSUE THREAD

**Issue by zeisss** [giantswarm/inago#38]
My editor warns me about our current names:

> task/task_service.go:14:6: type name will be used as task.TaskObject by other packages, and that stutters; consider calling this Object
> task/task_service.go:32:6: type name will be used as task.TaskService by other packages, and that stutters; consider calling this Service
> task/task_service.go:63:6: type name will be used as task.TaskServiceConfig by other packages, and that stutters; consider calling this ServiceConfig

I think I agree here. `TaskObject` could simply be `Task`, `TaskService` become `Service` etc.

Opinions @giantswarm/cena ?

**Comment by JosephSalisbury** [comment]
Sounds good - I'll ad `golint` to the CI tomorrow, so we can see these things easier.

**Comment by Nesurion** [comment]
Agreed as well. New names sound better.

**Comment by xh3b4sd** [comment]
No strong feelings.
