### ISSUE TITLE
getting status aggregation right

### ISSUE THREAD

**Issue by xh3b4sd** [giantswarm/inago#40]
We need to aggregate states to easily match whenever a unit is running, stopped or failed. I am checking the state matching between fleet and appd. There we compare fleet current state, systemd active and systemd sub state. In formica we decided to use fleet current and fleet desired, and systemd active. So why is that different and how to aggregate the state in formica then?

RFC @zeisss @JosephSalisbury

**Comment by xh3b4sd** [comment]
Here I tried to come up with some status aggregation. The values are translated from the ugly switch statements in appd to some more human readable code. What do you think? 

See https://github.com/giantswarm/formica/pull/41 for my aggregation solution.
See https://github.com/giantswarm/app-service/blob/master/service/scheduler-service/util.go#L35 for the ugly switch statements.

**Comment by zeisss** [comment]
For appd we want to have one status for the whole container chain. We want to map this to `stopped, starting, running, stopping, failed`. To get to the stopping/starting states, we need to inspect the sub state.

For formica we don't want one state - we are fine with showing the users the details (fleet cstate,dstate, systemd..). The aggregation here is information summary with the possibility to drill down.

I guess the `sub` state can be quite interesting as formica afaik would currently show one unit as running and the other two as dead, if we have  3unit group where the first unit is `starting`. Maybe we want to write down a few examples and what we want the endresult to look like.

This also has influence on the `waiting` stuff, as we want to wait for the sub state to be actually running, not `pre-start` or sthg.

**Comment by zeisss** [comment]
Closing as we have this for now. If we want to fine tune, lets make a new issue or just do it.
