### ISSUE TITLE
term instance is still unclear

### ISSUE THREAD

**Issue by xh3b4sd** [giantswarm/inago#60]
The idea of the term `instance` vs `slice` is not clear yet. See https://github.com/giantswarm/inago/pull/52#discussion-diff-55008342.

**Comment by JosephSalisbury** [comment]
@giantswarm/cena I'm not certain what is required here.

From `docs/terms.md`, we have:

```
### Instance
A group instance is a group in a fleet cluster. Having a group definition on
your local file system and deploying this using Inago to a fleet cluster,
creates a group instance. This group instance may be one of multiple slices.
```

It looks to me like the docs are saying that multiple `instances` make up a `group slice`. Is this correct?

**Comment by zeisss** [comment]
>  looks to me like the docs are saying that multiple instances make up a group slice. Is this correct?

Not in my head at least. thats the whole discussion. we have a group which is a) the folder on disk with the unit files and b) the virtual thing that can be addressed for start/stop/destroy which maps to either all slices or the single "slice" (when its an instance, so no `@` in the unit filenames)

**Comment by Nesurion** [comment]
current version of docs contain a clear definition in my opinion. Thoughts @giantswarm/cena

**Comment by JosephSalisbury** [comment]
I'd like to get @zeisss' opinion, but I think we're good enough for now. We will improve documentation as we go along.

**Comment by zeisss** [comment]
Lets go with this for now and wait for people to complain.
