### ISSUE TITLE
Write up contributing document

### ISSUE THREAD

**Issue by JosephSalisbury** [giantswarm/inago#7]
I'd like to actually write up a _useful_ (read: not copy and paste) contributing document, that explains our best practices when it comes to contributions.

My initial thoughts are:
- PRs must pass CI integration (this catches failing tests / go vet / go lint / whatever else we feel like putting in there - and automating this stuff is good)
- PRs must have a decent level of unit tests

Thoughts?

**Comment by JosephSalisbury** [comment]
ping @zeisss @xh3b4sd

**Comment by xh3b4sd** [comment]
Why not copy paste the one we have for all other open source repos?

**Comment by JosephSalisbury** [comment]
I have a concern that we'll just copy and paste it, and won't pay any attention to the actual content or readability, or whether all of it applies to the particular project.
I may be being too OCD about this :/

**Comment by xh3b4sd** [comment]
IMO some guys already cared about this. So I am out of here. IMO, lets copy/paste what we have and see what we need to do when we need to do something.

**Comment by zeisss** [comment]
We hav ehttps://github.com/giantswarm/inago/blob/master/CONTRIBUTING.md, good enough.
