### ISSUE TITLE
Improve validate command

### ISSUE THREAD

**Issue by JosephSalisbury** [giantswarm/inago#76]
- Command will attempt to validate a directory without any unit files in.
- Help text does not show that multiple group names can be specified.

**Comment by JosephSalisbury** [comment]
cc @xh3b4sd

**Comment by Nesurion** [comment]
things to improve:
see https://github.com/giantswarm/inago/pull/117

**Comment by zeisss** [comment]
Maybe also: Show multiple errors / warnings, instead of just one.

**Comment by Nesurion** [comment]
@zeisss could you elaborate?

**Comment by zeisss** [comment]
afaict the validate functions we have only return the first problem we see. We have the same logic in our API / CLI. Its annoying for the user to just see the first error, fix that, try again and then get the next error. 

Think about a compiler only showing you the first error it sees.

**Comment by Nesurion** [comment]
@zeisss got you, thanks.
