### ISSUE TITLE
update: Fix behaviour of --max-growth=0

### ISSUE THREAD

**Issue by xh3b4sd** [giantswarm/inago#80]
Might be the `--max-growth=0` flag is problematic. Having this setting given needs to remove slices first. It also needs to be validated if the settings are not destructive. When you have 2 slices running and `--min-alive=2` and `--max-growth=0` this will not work and should throw an error.

**Comment by JosephSalisbury** [comment]
https://github.com/giantswarm/inago/issues/105 is related to this

**Comment by zeisss** [comment]
TODO

> Might be the --max-growth=0 flag is problematic. Having this setting given needs to remove slices first.

This is covered by #105:

>  It also needs to be validated if the settings are not destructive. When you have 2 slices running and --min-alive=2 and --max-growth=0 this will not work and should throw an error.

**Comment by JosephSalisbury** [comment]
For clarity:
I'm working on checking - and fixing if this is not the case - the behaviour when max-growth is set to zero: for example, a group of two group slices, when updated with max-growth set to zero (and, assumedly, min-alive set to one), should have an update along the lines of:
- remove the first group slice
- create a new group slice
- remove the second group slice
- create a new group slice

**Comment by JosephSalisbury** [comment]
Yes, this isn't working currently:

```
core@core-01 ~ $ ls -R
.:
example  inagoctl

./example:
example-unit@.service
core@core-01 ~ $ cat ./example/example-unit\@.service
[Unit]
Description=Inago Demo Unit

[Service]
ExecStart=/bin/bash -c "while true; do echo Hi4; sleep 10; done"
core@core-01 ~ $ ./inagoctl submit example 2
2016-03-29 14:44:35.694 | INFO     | context.Background: Succeeded to submit group 'example'.
core@core-01 ~ $ ./inagoctl start example
2016-03-29 14:44:45.524 | INFO     | context.Background: Succeeded to start 2 slices for group 'example': [58e 952].
core@core-01 ~ $ vi ./example/example-unit\@.service
core@core-01 ~ $ ./inagoctl update example -v --max-growth=0 --min-alive=1
```

The update then hangs continuously.
