### ISSUE TITLE
Document build process

### ISSUE THREAD

**Issue by JosephSalisbury** [giantswarm/inago#9]
I want to (early on) document how to build / release the binary

**Comment by JosephSalisbury** [comment]
ping @xh3b4sd @zeisss

**Comment by xh3b4sd** [comment]
Documentation is a valid point in general. I want to prevent to write docs all day in the end. Documentation (as well as other important things like testing) need to be part of the daily business.

**Comment by JosephSalisbury** [comment]
Totally agree. What I'm trying to do is bring up what we need to document as it happens (in this case, we need to document the build process) as an actual issue, and act on it as soon as possible.
