### ISSUE TITLE
Test for Controller.Submit() broken

### ISSUE THREAD

**Issue by zeisss** [giantswarm/inago#92]
The test as it stands should :one: block forever, as the unit submitted is never returned by the fleet mock and :two: should at some point return that unit.

**Comment by JosephSalisbury** [comment]
I'm assuming this is a symptom of #91?

**Comment by zeisss** [comment]
Unclear to me. #91 is exactly the opposite of this. here I would it expect to bock, but it does not. in #91 it blocks, but it should not.

**Comment by JosephSalisbury** [comment]
Okay, I'll fix #91 today, and then we can see where we end up with this issue, as well as #96

**Comment by JosephSalisbury** [comment]
@zeisss i don't know what this issue requires.

**Comment by zeisss** [comment]
Can you look at the controller.Submit test? There is an inconsistency in the test setup, which when you think about it - should mean that the test SHOULD block forever.

**Comment by JosephSalisbury** [comment]
If you're talking about https://github.com/giantswarm/inago/blob/master/controller/controller_test.go#L547, I can't say I see it.

**Comment by zeisss** [comment]
Look at submit please. https://github.com/giantswarm/inago/blob/master/controller/controller_test.go#L518 vs https://github.com/giantswarm/inago/blob/master/controller/controller_test.go#L529

**Comment by Nesurion** [comment]
works as intended, but test coverage was bad. Fixed with #185
